name: Node.js CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: Build the project
        run: npm run build
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          
   deploy-to-dev:
    needs: build-and-scan
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - uses: actions/checkout@v2
    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.REGION }}  # Use the secret for flexibility
    - name: Deploy to AWS Amplify (Dev)
      run: |
        npm install -g @aws-amplify/cli
        amplify init --amplify "{ \"envName\": \"dev\", \"appId\": \"${{ secrets.AMPLIFY_APP_ID }}\" }" --yes
        amplify push --yes

  deploy-to-prod:
    needs: deploy-to-dev
    runs-on: ubuntu-latest
    environment: prod
    steps:
    - uses: actions/checkout@v2
    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.REGION }}
    - name: Deploy to AWS Amplify (Prod)
      run: |
        npm install -g @aws-amplify/cli
        amplify init --amplify "{ \"envName\": \"prod\", \"appId\": \"${{ secrets.AMPLIFY_APP_ID }}\" }" --yes
        amplify push --yes
