name: Node.js CI/CD Pipeline

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20' # Adjust the Node.js version as necessary
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test
    - name: SonarQube Scan
      id: sonarqube
      uses: SonarSource/sonarqube-scan-action@master
      with:
        args: >
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
    - name: Fail if quality gate failed
      if: steps.sonarqube.outcome == 'failure'
      run: exit 1

  deploy-to-dev:
    if: github.ref == 'refs/heads/develop'
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-1'
    - name: Deploy to AWS Amplify (Dev)
      run: |
        npm install -g @aws-amplify/cli
        amplify init --amplify "{ \"envName\": \"devamplify01\" }" --yes
        amplify checkout env devamplify01
        amplify push --yes

  deploy-to-prod:
    if: github.ref == 'refs/heads/main'
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-1'
    - name: Deploy to AWS Amplify (Prod)
      run: |
        npm install -g @aws-amplify/cli
        amplify init --amplify "{ \"envName\": \"prodamplify01\" }" --yes
        amplify checkout env prodamplify01
        amplify push --yes
